version: '3.8'
services:
  m3u8-downloader:
    build: .
    ports:
      - "7101:7101"
    volumes:
      - ./temp:/app/temp
      - ./uploads:/app/uploads
      - ./static:/app/static
      - ./templates:/app/templates
      - ./services:/app/services
      - ./models:/app/models
      - ./routes:/app/routes
      - ./handlers:/app/handlers
      - ./config.py:/app/config.py
      - ./app.py:/app/app.py
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONPATH=/app
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=ymbox
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=ymbox
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  debug:
    build: .
    command: python debug.py
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=ymbox
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: